# Generated by Django 4.2.4 on 2023-09-12 04:05

from django.db import migrations, models
import vamp_shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('vamp_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to=vamp_shop.models.get_image_upload_path),
        ),
    ]
