# Generated by Django 4.2.4 on 2023-09-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vamp_shop', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Make Me Glam', 'Make Me Glam'), ('Costumes', 'Costumes'), ('Decorations', 'Decorations'), ('Mehendi', 'Mehendi'), ('Party-Space', 'Party-Space'), ('Capture the moment', 'Capture the moment')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(choices=[('Groom', 'Groom'), ('Bride', 'Bride'), ('Indoor', 'Indoor'), ('Outdoor', 'Outdoor'), ('Mehendi', 'Mehendi'), ('Party-Space', 'Party-Space'), ('Capture the moment', 'Capture the moment')], default='', max_length=80),
        ),
    ]
