# Generated by Django 4.2.3 on 2023-08-17 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vamp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactpost',
            old_name='name',
            new_name='fname',
        ),
    ]
