# Generated by Django 4.2.4 on 2023-09-14 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vamp', '0003_usermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
