# Generated by Django 4.2.4 on 2023-09-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vamp', '0004_delete_usermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpost',
            name='email',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='contactpost',
            name='fname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='contactpost',
            name='subject',
            field=models.CharField(default='', max_length=50),
        ),
    ]
