# Generated by Django 4.2.4 on 2023-09-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vamp', '0005_alter_contactpost_email_alter_contactpost_fname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpost',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
