# Generated by Django 4.2.4 on 2023-09-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vamp', '0006_alter_contactpost_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_Images_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=300)),
                ('pub_date', models.DateField()),
                ('image', models.ImageField(default='', upload_to='index/about')),
            ],
        ),
    ]
