# Generated by Django 4.2.4 on 2023-09-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vamp', '0007_about_images_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index_FAQ_Quastions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quastion', models.CharField(max_length=50)),
                ('answer', models.CharField(max_length=300)),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Index_Gallery_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='index/gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Index_Service_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('pub_date', models.DateField()),
                ('image', models.ImageField(default='', upload_to='index/services')),
            ],
        ),
        migrations.RenameModel(
            old_name='About_Images_Model',
            new_name='Index_About_Images',
        ),
    ]
