# Generated by Django 4.2.4 on 2023-09-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vamp', '0008_index_faq_quastions_index_gallery_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index_service_images',
            name='image',
            field=models.ImageField(default='', upload_to='index/service'),
        ),
    ]
