# Generated by Django 4.2.4 on 2023-09-14 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vamp', '0009_alter_index_service_images_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Index_FAQ_Quastions',
            new_name='Index_FAQ_Questions',
        ),
        migrations.RenameField(
            model_name='index_faq_questions',
            old_name='answer',
            new_name='answers',
        ),
        migrations.RenameField(
            model_name='index_faq_questions',
            old_name='quastion',
            new_name='question',
        ),
    ]
