# Generated by Django 4.2.4 on 2023-09-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vamp', '0010_rename_index_faq_quastions_index_faq_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index_faq_questions',
            name='answers',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='index_faq_questions',
            name='question',
            field=models.TextField(),
        ),
    ]
