# Generated by Django 4.2.4 on 2023-09-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vamp', '0012_alter_index_faq_questions_answers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index_faq_questions',
            name='answers',
            field=models.CharField(max_length=550),
        ),
        migrations.AlterField(
            model_name='index_faq_questions',
            name='question',
            field=models.CharField(max_length=350),
        ),
    ]
