# Generated by Django 4.2.4 on 2023-09-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vamp', '0013_alter_index_faq_questions_answers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index_about_images',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='index_about_images',
            name='headline',
            field=models.CharField(max_length=100),
        ),
    ]
